### ISSUE TITLE
Consider alternative approach so that we don't need a split Speed value

### ISSUE THREAD

**Issue by digi-brain** [GameBrains/er-core#10]
Currently we're working with a split Speed value for abilities like Cavalry and Jump Packs. It works, but it'd be nice if we can make a 'cleaner' approach work.
We've discussed a possible alternative a bit — it may or may not work better, so we'll need to experiment.

Rather than delay publication of changes in #8, I'm happy for us to experiment with this in another branch or at a later time -- though I do think we should do it fairly soon.

**Comment by IJW-Wartrader** [comment]
The movement branch, when it's started, would be the sensible place to look at this again. But I suspect we have different ideas of what 'cleaner' looks like ;-)

We're working within three constraints. Some are self-imposed, but still important:

- The Speed characteristic in the detachment builder and in unit summaries needs to show that the unit moves differently than expected for its unit type. At a minimum, this can be an asterisk or other footnote character linking to the relevant ability in the Notes.
- 'Cavalry' units with out a base unit exist.
- The original Cavalry ability has already been split in two. Splitting it into three is going to make some of the Notes areas extremely crowded, notably Rough Rider HQs which can already hit 'Save, Psyker, (Armour +1, Assault, Cavalry, Hero)'.

**Comment by digi-brain** [comment]
>But I suspect we have different ideas of what 'cleaner' looks like ;-)

Lol, quite likely, but I do feel like an alternative **may** offset some of the other issues better. The split Speed idea has forced to insert a number of related clarifications.

---

>At a minimum, this can be an asterisk or other footnote character linking to the relevant ability in the Notes.

If that is necessary, I see no harm in it.

---

>'Cavalry' units with out a base unit exist.

Yup, I was thinking that as I edited your draft. But I figured we'll gloss over it for now. This might shake it out better in this experiment, or even if the experiment fails we might rough out a better way to handle 'cavalry that doesn't have a base unit'.

---

>Splitting it into three is going to make some of the Notes areas extremely crowded

Indeed. As we previously discussed, this experiment might go as far as 'cancelling' the breakdown of Cavalry into parts and treat it more like Heavy Weapons. This might indeed turn out to be 'cleaner' if the rest of the idea hangs together okay.

**Comment by digi-brain** [comment]
Another somewhat related thing is that trying to split things between 'Data sheet modifiers' and 'Unit abilities' does not work well because several things fall into both categories (eg, Hero). This is perhaps another hint that we should look for a better way and that these categories should not block us from possible alternative options.

**Comment by IJW-Wartrader** [comment]
I get your point, but Hero is irrelevant as the in-game part is done by adding the separate Save ability to the data sheet, rather than being an effect that's written within Hero.

So Hero is fine as a 'pure' Data sheet modifier.

**Comment by digi-brain** [comment]
That's true -- I sort of realised that as I was writing the above. It's still a bit messy to look up though -- your mind wants to look at one alphabetical list, not sort between two (well, four, but I've only stumbled on the two that relate to units). It is still messy for Jump Packs and Cavalry too, which you've already acknowledged. Anyway, we'll see how it pans out in an experiment.

Even aside from this experiment (though not in the current PR), I think it'd probably be better to put all abilities into a single series of lists something like this:

- Special abiltiies
-- Abilities A to G
-- Abilities G to P
-- Abilities P to Z

...and then mark each ability in some way to identify which categories they relate to. This would be easier to look up, plus we can 'tag' abilities in more than one category.

**Comment by digi-brain** [comment]
Added new branch to experiment with alternatives: `no-split-speed-value`

In my current experiment on this branch:

- I've created a new ability with keyword attribute {swift}.
- Much as {hero} uses {save}, {cavalry} and {jump-packs} use {swift}.
 
I think it works, and it accounts for the likes of Kroot Hounds too (they'd have {swift} and have VEH on their data sheet, but not have {cavalry}).

We may want to back up a little more and make {cavalry} include {armour-1} too, to mirror the original rules. This approach to abilities within abilities might give us a reasonably neat way to have our cake and eat it — break stuff out for the design space, but not clutter the data sheets with umpteen itty bitty abilities, while still keeping it quite easy to understand.

As it is only one line anyway, I've repeated the {swift} ability rule in {cavalry} and {jump-packs}. If we like this approach, we'd create a partial of course, and extend the idea to other abilities (at least, where the rule is short).

See what you think.

**Comment by IJW-Wartrader** [comment]
Unfortunately, some of these changes contradict the purposes behind adding a split Speed value, and moving the Armour bonus out of Cavalry. :-(

> * I've created a new ability with keyword attribute {swift}.
> * Much as {hero} uses {save}, {cavalry} and {jump-packs} use {swift}.

'Swift' **will** have to be listed in the Notes section of all Cavalry units in the detachment printer, in the same way that Save is listed in the Notes of all units with Hero. It's an in-game ability, so it has to be listed in its own right when someone prints out their army list.

So this:
> * The original Cavalry ability has already been split in two. Splitting it into three is going to make some of the Notes areas extremely crowded, notably Rough Rider HQs which are already 'Save, Psyker, (Armour +1, Assault, Cavalry, Hero)'.

Becomes 'Psyker, Save, *Swift, (Armour +1, Assault, Cavalry, Hero)'.

> We may want to back up a little more and make {cavalry} include {armour-1} too, to mirror the original rules. This approach to abilities within abilities might give us a reasonably neat way to have our cake and eat it — break stuff out for the design space, but not clutter the data sheets with umpteen itty bitty abilities, while still keeping it quite easy to understand.

The purpose of moving Armour +1 out of Cavalry is to allow Fleshhounds and Chaos units on Discs (plus potential future units) to become Vehicles and gain the extra charge Speed, _without_ getting the Armour bonus. 

So we _can_ move the Armour bonus back into Cavalry, but it will mean adding another itty bitty Data sheet modifier ability to change unit types to Vehicle, because I want these units to remain Vehicles with the resulting effects on terrain and transportation. ;-)

A minor note on the name - 'Swift' as a name is misleading. While it's making Vehicle units faster on the charge, for Jump Packs Infantry, it's making them _slower_ than expected on the charge because they get Speed x1.5 instead of Speed x2. This was one of the smaller reasons for choosing the split Speed values approach, we don't have to think up yet another ability name that has to be clear enough to remind players of what it means.


### Summary

- It's going to make the Notes sections of a substantial number of units more cluttered, while at the same time removing information from the unit's characteristics.
- Moving Armour +1 back into Cavalry means adding a new 'unit type = VEH' ability. This reduces Notes clutter slightly, but only back to the same level as they are now with a split Speed value.
- The new ability name is likely to need changing, but that's a minor issue.

**Comment by digi-brain** [comment]
>'Swift' **will** have to be listed in the Notes section of all Cavalry units and jump Packs unit in the detachment printer, in the same way that Save is listed in the Notes of all units with Hero. It's an in-game ability, so it has to be listed in its own right when someone prints out their army list.

I disagree. You're treating some things as immutable when I don't think they are.

- While I agree that it is important to think about how we might do things in the detachment printer, I don't think that we should have the tail wagging the dog. It may be that you need to find another way to do things there rather than have it dictate how we do the rules. I don't like the idea that this or that is **automatically** out of bounds because it "must" or "can't" happen based on how you picture the detachment printer working.
- Your logic doesn't seem to be consistent anyway. I note that you don't propose to print {save} alongside {hero}... same principle. And Heavy Weapons isn't [Range(45), Firepower +1] either.
- Plus we have the asterisk as a reminder for Swift.
- Plus without Swift we'd still have to work out how to apply cavalry in a way that works for Kroot Hounds. (Not saying that can't be done, or that there isn't yet another way that doesn't involve split Speeds.)

---

>The original Cavalry ability has already been split in two.

Yeah, I'm saying we might need to back up and **not** split it, just as we haven't with Heavy Weapons. We can still have Armour +1 for unit design purposes, but it is separate to Cavalry. Thus we do not exclude:

>Fleshhounds and Chaos units on Discs (plus potential future units) to become Vehicles and gain the extra charge Speed, without getting the Armour bonus

Plus note that where there is no base unit, we can just add VEH directly into the data sheet anyway - no need for an ability just for that purpose. So, Kroot Hounds and such have VEH on their data sheet and the {swift} ability -- job done.

---

>A minor note on the name - 'Swift' as a name is misleading. While it's making Vehicle units faster on the charge, for Jump Packs Infantry, it's making them slower than expected on the charge because they get Speed x1.5 instead of Speed x2. This was one of the smaller reasons for choosing the split Speed values approach, we don't have to think up yet another ability name that has to be clear enough to remind players of what it means.

I think this **is** minor, yes... **at worst**. Most things that would have this ability have double Speed value relative to a base unit, so they are indeed faster than their base units and therefore definitely 'swift'. It's only Kroot Hounds and such that are awkward, and even then they are still fundamentally 'swift' - it's just built directly into their profile already because they have no base unit. I think it is a non-issue really, not misleading.

But in any case, I'm sure we could find another name if we need to. This is work in progress and nomenclature shouldn't be a barrier to the fundamental idea.

**Comment by IJW-Wartrader** [comment]
OK, there's still some kind of fundamental miscommunication happening here.

Here are the constraints and edge-cases again, listed in more detail:

- All in-game abilities need to be listed in the Notes section of a unit when displaying the 'full' version of the unit, or printing out a player's army.
- Kroot Hounds and equivalents need unit type: VEH and charge Speed x1.5. They **don't** have a base unit. Swift and split Speed values both work for this.
- Fleshhounds and equivalents need unit type: VEH, charge Speed x1.5, and no Armour bonus. They **do** have a base unit. Swift and split Speed values both work for this. A recombined Cavalry ability **cannot** do this because of the Armour bonus.
- We have to find a balance between the number of abilities that we have in the game, and how cluttered the Notes section gets for individual units.

---

> I disagree. You're treating some things as immutable when I don't think they are.
> 
> * While I agree that it is important to think about how we might do things in the detachment printer, I don't think that we should have the tail wagging the dog. It may be that you need to find another way to do things there rather than have it dictate how we do the rules. I don't like the idea that this or that is **automatically** out of bounds because it "must" or "can't" happen based on how you picture the detachment printer working.
> * Your logic doesn't seem to be consistent anyway. I note that you don't propose to print {save} alongside {hero}... same principle. And Heavy Weapons isn't [Range(45), Firepower +1] either.
> * Plus we have the asterisk as a reminder for Swift.
> * Plus without Swift we'd still have to work out how to apply cavalry in a way that works for Kroot Hounds. (Not saying that can't be done, or that there isn't yet another way that doesn't involve split Speeds.)

- Forget all mentions of the detachment printer. That's irrelevant. I'm talking about all situations where we display a 'full' data sheet profile to the player. Anything that is an in-game ability needs to be shown to the player when they look at the unit. That's absolute basic first principles of game design. I don't know why GW decided to flout it, but I've seen multiple games of E40k where players forgot in-game abilities because they were nested inside other abilities and not listed.
- I **do** print Save alongside Hero, because of this principle. I've said that I do, multiple times, and you can see it in the printer. Heavy Weapons is not equivalent because it only changes characteristics values and doesn't contain in-game abilities. Hero and Heavy Weapons work in fundamentally different ways, so are treated differently.
- An ability (called 'Swift' in this case) and a split Speed value perform the same function here. One of the reasons why I rejected the idea of making it an in-game ability is that it's adding an extra layer of abstraction, and removing information from the data sheet.
- We don't need to apply Cavalry to Kroot Hounds. They get listed as VEH and a split Speed value (or Swift), job done. In this instance, split Speed values and Swift are performing an identical function, they're just displaying it to the player differently.

---

> > The original Cavalry ability has already been split in two.
> 
> Yeah, I'm saying we might need to back up and **not** split it, just as we haven't with Heavy Weapons. We can still have Armour +1 for unit design purposes, but it is separate to Cavalry. Thus we do not exclude:
> 
> > Fleshhounds and Chaos units on Discs (plus potential future units) to become Vehicles and gain the extra charge Speed, without getting the Armour bonus
> 
> Plus note that where there is no base unit, we can just add VEH directly into the data sheet anyway - no need for an ability just for that purpose. So, Kroot Hounds and such have VEH on their data sheet and the {swift} ability -- job done.

See the more explicitly spelled-out restrictions and edge-cases at the top of this post.

Fleshhounds, Chaos Sorcerer on Discs, and equivalent units _have base units_. Daemons for Fleshhounds, and Chaos Space Marines for Chaos Sorcerers, Discriders etc. We can't just add VEH directly to their data sheets.

Please note that I'm not dead-set against the idea of recombining Cavalry, but it's a separate issue from Swift vs split Speed values, and recombining Cavalry will require adding a new 'unit type: VEH' Data sheet modifier ability.

**Comment by IJW-Wartrader** [comment]
> * Forget all mentions of the detachment printer. That's irrelevant. I'm talking about all situations where we display a 'full' data sheet profile to the player. Anything that is an in-game ability needs to be shown to the player when they look at the unit. That's absolute basic first principles of game design. I don't know why GW decided to flout it, but I've seen multiple games of E40k where players forgot in-game abilities because they were nested inside other abilities and not listed.

Just so this doesn't get lost in an edit...

When I say that we need to list all in-game abilities in the full display version of a data sheet, I'm **not** saying that this automatically excludes using Swift as an in-game Unit ability, instead of using split Speed values as a characteristic change. 

I'm pointing out that this increase in the number of abilities listed in the Notes section needs to be taken into account when weighing up the pros and cons of different approaches.

**Comment by digi-brain** [comment]
Okay, thanks for spelling out your point of view and baseline assumptions some more. And apologies for where I occasionally miss something that **is** in plain sight (eg, printing {save} and {hero} together).

---

>Fleshhounds, Chaos Sorcerer on Discs, and equivalent units have base units. Daemons for Fleshhounds, and Chaos Space Marines for Chaos Sorcerers, Discriders etc. We can't just add VEH directly to their data sheets.
>
>Please note that I'm not dead-set against the idea of recombining Cavalry, but it's a separate issue from Swift vs split Speed values, and recombining Cavalry will require adding a new 'unit type: VEH' Data sheet modifier ability.

Okay, gotcha. They are tricky little blighters aren't they? I will concede that you have a better handle on these details than me; still, I'm hopeful (but far from certain) that we might be able to find a more elegant solution.

---

>When I say that we need to list all in-game abilities in the full display version of a data sheet, I'm not saying that this automatically excludes using Swift as an in-game Unit ability, instead of using split Speed values as a characteristic change.
>
>I'm pointing out that this increase in the number of abilities listed in the Notes section needs to be taken into account when weighing up the pros and cons of different approaches.

Okay, good to know. I agree in principle, but given that we're not able to design from the ground up with every best practice, sometimes the best overall solution might be to accept some compromises -- 'better than the original' and 'better overall given all the limitations we're stuck with' might be better than holding ourselves too rigidly to the best practices in rules design, however worthy they may be.

So for example, one compromise that **might** be might be better overall is to duplicate 'sub-ability' rules text (like Swift or Save) into an ability that reuses it (like Jump Packs or Hero). Then at least the player can see the 'full ability' in one place, and the fact that part of it has commonality elsewhere is just 'nice to know' and an aid to memory. Just this would still be an improvement on the original, in which these things in common aren't spelled out as such and so it is harder in the original to remember which elements actually were identical, or not.

So, best practices should be plan A; but I feel that we should be open to the idea that some compromise on the best practices **might** actually produce a better solution overall, plan B.

---

I'll stew/experiment on all this some more when I get time.

**Comment by IJW-Wartrader** [comment]
> Okay, thanks for spelling out your point of view and baseline assumptions some more. And apologies for where I occasionally miss something that **is** in plain sight (eg, printing {save} and {hero} together).

No worries. Printing {save} and {hero} together was particularly annoying because it's right there in the Rough Rider example up-thread. But I know myself just how easy it is to miss things in plain sight... :-(

---

### Cavalry

I'm coming round to the idea of recombining Cavalry, _without_ adding a new 'unit type: VEH' Data sheet modifier ability. It's going to be more familiar for existing players, and makes the Notes section cleaner for a large number of units.

Fleshhounds with Armour 5+ I can live with, and Bloodcrushers (Bloodletters of Juggernauts) would still be distinguished by having {rampage} compared to Fleshhounds.
Disc-riding CSM having Armour 6 is more of a stretch, but that's a vanishingly-small number of units.

The {armour-1} ability would still be needed, but would only be used by new units like Meganobz and possibly Beasts of Nurgle. I also suspect it'll be very handy when adding 'modern 40k' units like Centurions.

**Comment by digi-brain** [comment]
>I'm coming round to the idea of recombining Cavalry, without adding a new 'unit type: VEH' Data sheet modifier ability. It's going to be more familiar for existing players, and makes the Notes section cleaner for a large number of units.

It does rather look that way doesn't it. I think we were right to experiment with it, but it does seem to be more trouble that it is worth. Though I'm starting to wonder whether we shouldn't abandon unit data sheet modifiers altogether (except as design guidelines) and just make all unit data sheets 'direct' rather than 'derived'... we want to print them explicitly anyway, so perhaps the whole 'base unit' thing is too limiting and carries little real value in the end?

Meanwhile, I might be coming around to more acceptance of split Speed value. I'll experiment some more when I get time, but I can see that all the fiddly edge cases you've outlined do indeed make it... challenging... and that the 'cost' of more info in the Speed column could well be the lesser evil.

However, short of a breakthrough on that, it does seem like split Speed value will get the job done. And in that case, as my friend pointed out over the weekend, why not go the whole hog and add split speeds to infantry units too? Did you consider that already?

**Comment by IJW-Wartrader** [comment]
> It does rather look that way doesn't it. I think we were right to experiment with it, but it does seem to be more trouble that it is worth. Though I'm starting to wonder whether we shouldn't abandon unit data sheet modifiers altogether (except as design guidelines) and just make all unit data sheets 'direct' rather than 'derived'... we want to print them explicitly anyway, so perhaps the whole 'base unit' thing is too limiting and carries little real value in the end?

We still need them for the detachment lists, as I think there's a strong case for listing, for example, Librarians as 'Space Marine unit (Hero, Psyker)', 'Bike unit (Hero,Psyker)' etc.


> However, short of a breakthrough on that, it does seem like split Speed value will get the job done. And in that case, as my friend pointed out over the weekend, why not go the whole hog and add split speeds to infantry units too? Did you consider that already?

I have been wondering about it. For now, I thought it's OK to leave standard Infantry Speeds as they are for familiarity and because 'Infantry = double charge Speed' is simple enough.

But that's something we can change _relatively_ simply later on. That could be a good one to ask players about after we've got a completed site.

I've been considering using the split Speed display for units with Walker, though, to reinforce that they're not moving like Vehicle units.

**Comment by digi-brain** [comment]
>We still need them for the detachment lists, as I think there's a strong case for listing, for example, Librarians as 'Space Marine unit (Hero, Psyker)', 'Bike unit (Hero,Psyker)' etc.

Yes, but those aren't 'pure' data sheet modifiers, so they still have a place. In fact, we could even junk Hero and just have Save instead, because we'd print the new Assault value directly into the data sheet and the rest of the ability is in fact Save anyway.

So, rather than present this:
`Up to one Space Marine Librarian: 35 points | Consists of 1 Space Marine unit ( Psyker, Hero)`
`Space Marines | 10 cm | 30 cm | 1 | 3 | 5+ | Rapid Fire`
`Space Marine Librarian | As Space Marines unit | +Hero, + Psyker`

...we'd present this:
`Up to one Space Marine Librarian: 35 points | Consists of 1 Space Marine Librarian unit`
`Space Marines | 10 cm | 30 cm | 1 | 3 | 5+ | Rapid Fire`
`Space Marine Librarian | 10 cm | 30 cm | 1 | 6 | 5+ | Rapid Fire, Psyker, Save`

---

I agree that we don't **have** to change the split Speed value stuff now and can always do it later. But I do also think that — unless we find an alternative pretty soon — then we might as well present it in its 'full' form fairly soon. While the double move bit is simple for Infantry (and by extension, Walker units), it'd still be neater and clearer to treat all data sheets the same way. Then players can see all 'special' charge moves at a glance and we can cut down the 'special charge move Speed bonuses' text a little at `assault-moves-and-charges.adoc`. 

And the fact of the Walker ability reinforces this — it's another thing that provides a special charge move that we didn't cover in that topic. So all in all, if we're on that path then I think it'd be much clearer to go the whole hog and put the split Speed value on everything that has it (so, everything except non-Walker vehicle units and War Engine units). Why give players the info 'at a glance' for some units and not for some others, when the same principle is at work?

**Comment by digi-brain** [comment]
Extended example:

So, rather than present this:
`Up to one Space Marine Librarian: 35 points | Consists of 1 Space Marine unit ( Psyker, Hero)`
`Upgrade to jump packs ( Hero, Psyker, Jump Packs)*: Free`
`Upgrade to Bike unit (Psyker, Hero)*: Free`

`Space Marines | 10 cm | 30 cm | 1 | 3 | 5+ | Rapid Fire`
`Space Marine Librarian | As Space Marines unit | +Hero, + Psyker`
[Plus the other data sheets exist in reality, but are only **implied** in the source material.]

...we'd present this:
`Up to one Space Marine Librarian: 35 points | Consists of 1 Space Marine Librarian unit`
`Upgrade to Jump Packs*: Free`
`Upgrade to Bike unit*: Free`

`Space Marines | 10 cm | 30 cm | 1 | 3 | 5+ | Rapid Fire`
`Space Marine Librarian | 10 cm | 30 cm | 1 | 6 | 5+ | Rapid Fire, Psyker, Save`
`Space Marine Librarian Jump Packs | 20/30 cm | 30 cm | 1 | 6 | 5+ | Rapid Fire, Jump Packs, Psyker, Save`
`Space Marine Librarian Bike | 35 cm | 15 cm | 1 | 2 | 4+ | Psyker, Save`

That doesn't seem too bad, given that similar extra profiles already exist — we'd just be making them explicit (and thus more clear) while we'd also get free of a constraint that ties us up in knots.

**Comment by IJW-Wartrader** [comment]
From previous discussions, you're losing the _purpose_ of Librarians being listed as `Space Marine unit ( Psyker, Hero)` in the detachment lists.

It allows the player to see exactly what unit they're getting, without having to memorise every individual data sheet, or having an excessively long unit summary table open at the same time.

Bear in mind that there are already more than 20 different Space Marine Infantry HQs, plus a dozen HQs that are Vehicles.

**Comment by digi-brain** [comment]
Yes, but what I'm wondering is whether that purpose really justifies the other challenges and compromises that it throws up when we try to improve and extend things. It's a unique aspect of this edition, but one that might be more trouble than it is worth.

Let's face it - those of us who play these sorts of games are well used to lots of data sheets anyway. None of the other editions of Epic have this 'base unit' feature, and we manage just fine with all the additional data sheets in those editions. The 'As X, plus Y' idea is nice, but limiting and not consistent anyway — once you get past Imperial forces, 'As X, plus Y' doesn't get used for all that many variations, and lots of things don't use it **at all**.

Depending on how we present it and where, we can still show the 'commonality' as an aid to memory, as I've said before.

As I say, all these profiles do actually exist in reality, we're just making them explicit and then 'aid to memory' tricks in presentation are a bonus. [Also, a hybrid approach might also work where the abilities **don't** have a data sheet modifying element.]

So then, "20 different Space Marine Infantry HQs, plus a dozen HQs that are Vehicles"... so what? Maybe this is the lesser evil compared to the other compromises we face, and making them explicit has virtues (as with split Speed values)? And it's not like no-one has ever asked why the data sheets can't just be explicit either.

**Comment by IJW-Wartrader** [comment]
Sorry for the rather curt reply earlier, I should have waited until I had time to reply properly.

There are a number of issues involved here, not all of which are related to rules. 

ADHD places some severe constraints on how I can work. I have an _enthusiastic_ setting and a _zero enthusiasm_ setting, and very little in between. The _zero enthusiasm_ setting is, literally, on the level of 'I wouldn't do X even if you paid me', and the enthusiasm is finite. Once it runs low, all that's left is _zero enthusiasm_. The enthusiasm can run out unexpectedly if things aren't going well, so I have to take measures to protect it. One of the biggest saps on my enthusiasm is tasks that look endless or too open-ended, or where work that's already been done has to be redone multiple times.

So every time you re-open a discussion that I thought had been discussed in depth and settled, loads of warning klaxons go off. It's not just that a barely-manageable task (aka the first minimum-working version of Remastered) suddenly becomes unmanageable because I don't know which completed tasks and decisions are going to stay completed, but also because I work by having a detailed mental model of the game mechanics and they're going to be presented, and each re-opened issue takes away the foundations of that model.

We have a **huge** amount of work still to do for a minimum-working version of Remastered:
- Almost the entire war engine sub-section.
- A minimum of some of the generic scenarios and the scenario special rules from the Battles section.
- Rewriting the Fate cards and redesigning the quick reference sheet.
- Laying out several dozen war engine datasheets, probably in two formats. (Ignoring future plans like a website function that lets users add their own names and photos for each war engine, and generates a printable page with them all on.)
- Checking through the whole of the Core Rules section for rules issues.
- At least _part_ of the Armies book, in terms of describing each army's overall structure, any faction-level rules, and some unit summaries. We can get away without the full detachment lists to start with, as they overlap so much with the detachment builder.

I would **very** much like to get more of that done, before we take parts of the game that currently work and redoing them almost from scratch.

**Comment by IJW-Wartrader** [comment]
On to specific points.

> Yes, but what I'm wondering is whether that purpose really justifies the other challenges and compromises that it throws up when we try to improve and extend things. It's a unique aspect of this edition, but one that might be more trouble than it is worth.

One. Could you be more specific about the challenges and compromises? I don't want to try second-guessing which bits you're referring to. As far as I'm concerned, we've currently 'fixed' the outstanding issues and have a system that works, especially once we've implemented your suggestion of putting all the abilities back into one list and tagging them by type.

Two. One of the reasons why we're rewriting Epic 40,000 is because of its unique aspects which don't exist in other editions. I think we need to be _really_ careful about removing any of those unique aspects in the 'rewrite' version. A hypothetical 'completely new edition inspired by E40k' would be another matter, but that's not what we're currently working on. Beware of scope creep! ;-)

---

> The 'As X, plus Y' idea is nice, but limiting and not consistent anyway — once you get past Imperial forces, 'As X, plus Y' doesn't get used for all that many variations, and lots of things don't use it **at all**.

I politely suggest that you go and look again. Apart from the Tyranids, and parts of the Tau, 'Base unit X + Y' is **extremely** widely and consistently used. It's to be expected that Tyranids don't use it much, because almost every unit is a different species. Where they are mostly one species like the Genestealer Cult list, they use the system. Squats, for example, only have a single Infantry base unit with variations, plus a support weapon. Even Tau use the system extensively for Kroot units.

---

> Depending on how we present it and where, we can still show the 'commonality' as an aid to memory, as I've said before.
> 
> As I say, all these profiles do actually exist in reality, we're just making them explicit and then 'aid to memory' tricks in presentation are a bonus. [Also, a hybrid approach might also work where the abilities **don't** have a data sheet modifying element -- or yet a different hybrid approach that can include cover special cases like Hero.]

As a reminder, this was the result of the previous discussion:
- Unit summary tables will use fully explicit data sheets, with Data sheet modifiers listed in brackets to show that they've already been applied. The unit summary tables will only show the most common units, because there are something like 400 unique variants so far, excluding war engines.
- The army list printer will use fully explicit data sheets, with Data sheet modifiers listed in brackets to show that they've already been applied. By definition, every unit is included.
- The detachment lists and the individual detachment pages on the list builder site will use 'Base unit X + Y' terminology.

The unit summaries and the printed army lists will show:
```
Space Marine Librarian | INF | 10 cm | 30 cm | 1 | 6 | 5+ | Rapid Fire, Psyker, Save (Hero)
Space Marine Librarian on Bike | VEH | 35 cm | 15 cm | 1 | 2 | 4+ | Psyker, Save (Hero)
```

So `Space Marine Librarian | As Space Marines unit | +Hero, + Psyker` will not be used anywhere, just `Space Marine unit ( Psyker, Hero)`.

**Comment by digi-brain** [comment]
Wow. Your 'curt reply' seemed okay to me, but your follow up…

I don't know much about ADHD. However, I feel that some of your messages have been quite aggressive. You've talked about how you can't work a certain way and your enthusiasm. Well, this environment is not fun for **me** either, and not conducive to **my** best work…

I get some of what you're driving at, but I feel that you need to consider how you convey your frustrations, and that other parties might also be feeling frustrated at the same or different points. My experience is that your reactions are sometimes extreme. I've tried to make allowances for this and to be understanding.

However, it seems that I have a choice: Give you space to work mostly on your own, or not work with you at all. I'd prefer the first choice over the second, as long as we can make it work.

On the plus side, more narrowly defined roles with little direct collaboration means less faster progress in theory because we have less of the conversational back-and-forth.

So, how about this:

1. I will continue to make 'first pass' redrafts of the original content as and when I find the time.
2. You can work on remastering the rules, largely without input from me. Where they exist, you will use my redrafts as a start point of course, and where they don't exist you can make a first pass at it yourself while you work on the actual rules issues. You compose the rules content as you think best per the map that you have in your head. We will not explore thought experiments that **might** imply challenge to the paradigm any more.
3. I will edit style and information architecture, largely without input from you. If I deem it most expedient to leave an editing issue as-is for the moment pending improvement at some later date, I will. If I deem it most expedient to edit something there and then, I will. I will not debate these things with you anymore — except where a truly 'rule-breaking' interpretation is at stake.

Notes/reminders on some things that you need to accept or else we're going nowhere:

- As a technical writer, I **will** rewrite your text to make the rules overall easier to find, understand and use.
- As a rules SME, you will sometimes need to explain your logic and how things interact, and you won't always be able to pre-empt all possible misunderstandings and mistakes. Some iteration is inevitable.
- Yes, of course you can and should point out, with some **grace** please, cases where I mistakenly harm the interpretation of the rules — just as I will sometimes highlight or address errors or unwanted interpretations that you may not have considered. We find and fix these things together. Neither of us are infallible.
- I encourage you to see the Contributor's Guide and the A to Z of style as an imperfect but useful aid, rather than as some encumbrance that can't possibly be 'right' if it doesn't match your preconceived ideas.

**Comment by digi-brain** [comment]
Okay, things got a bit tense, but we've smoothed things out in video chat. :-D

I'm happy to close this particular issue — I concede that **if** there is a worthwhile alternative to split Speed values then it seems like it will take more time to thrash out than it is worth at the moment.

We can always re-open the issue if we have some other brainwave or if we actually do find that we want to challenge the paradigm of base units. I won't delete the branch yet as I want to check it for one or two small tweaks that may still be worthwhile outside of this issue — but I'll probably delete it in due course so we don't end up with lots of redundant branches cluttering things up.
