### ISSUE TITLE
Special Abilities August Edition

### ISSUE THREAD

**Issue by IJW-Wartrader** [GameBrains/er-core#23]
Issue to go with the new Special Abilities editing branch:
https://github.com/GameBrains/er-core/tree/special-abilities-august-2021

**Comment by IJW-Wartrader** [comment]
First commit done and uploaded.

**Comment by IJW-Wartrader** [comment]
Supreme Commander updated with the extra ability for the Tyranid Dominatrix, but that text is still rough...

**Comment by IJW-Wartrader** [comment]
Terminology question, rolling to see who wins an assault.

Do you have any strong opinions on giving this roll a specific name? For preference, the combat resolution roll, as that's what I automatically call it and that seems to be fairly common.

Why? Because it makes the Supreme Commander re-roll text (and Fate Card re-roll texts) a bit 'cleaner' and less ambiguous. When I first read the Fate Cards I thought it was talking about rolling to hit the enemy!

**Comment by digi-brain** [comment]
I've only just seen this — by default, only the person who posts an issue is subscribed to notifications, and I haven't actively checked or stumbled across the issues list in ages.

A specific name for the 'combat resolution roll' seems like a good idea to me — I can't think of any drawback, and as you say, it'd help other rules texts to tie in more neatly/unambiguously.

**Comment by IJW-Wartrader** [comment]
@digi-brain on a related note, do you have any formatting preferences for optional rules?

While updating the two combat resolution pages (CC and Firefight) to call it a combat resolution roll, I'd like to mention the option of rolling two dice and picking the highest. I'm hesitant to simply add it in as the default because previous discussions weren't decisively in favour (for example https://www.facebook.com/groups/1952676958177757/posts/3622915814487188/).

Add it as a TIP, NOTE, or NOTE.e40k?

**Comment by digi-brain** [comment]
@IJW-Wartrader Hmm... might have to think about that a little.

We could of course put all optional rules in a separate section, much like the experimental rules (and much like the "House rules and [blah blah]...." section in the original rulebook, except that we use some relationship links too).

Or, at least some optional rules could be in the main content as you're suggesting. I'm not sure what should qualify for this treatment, versus what should qualify for the above. But if/where we do decide to take this route then I think the best thing is probably to have another note style especially for this purpose — perhaps `NOTE.option` or `NOTE.optional`? (I don't think that the semantics of it fit well with TIP.)

In this particular case, given the mixed response to the idea, indeed I don't think that we should add it as the default. 

For what it's worth: My friend and I are among those who don't like the 2xD6 idea. We discussed it again at the weekend, and opted again for the original 1xD6 method. Perhaps to some extent one's opinion here may change as a function of how many games one gets to play, but as it was we felt okay with how it played out. We didn't find the 2xD6 method appealing — mainly because we don't like how it dramatically increases the chance that the player with the upper hand will get an **unbeatable** score.

**Comment by IJW-Wartrader** [comment]
I agree, a NOTE subset makes more sense.

> We didn't find the 2xD6 method appealing — mainly because we don't like how it dramatically increases the chance that the player with the upper hand will get an **unbeatable** score.

Hmm. Depends on what you mean by 'dramatically'. The actual odds of the lower player drawing or better change by:

Down by 5, 2.8% to 0.8%
Down by 4, 8.3% to 4.1%
Down by 3, 17% to 11%
Down by 2, 28% to 22%

Obviously there's a big shift when you're down by five, but I think the chance of not losing in that situation should be _extremely_ low.

**Comment by digi-brain** [comment]
I'm not sure how you calculated these numbers, and I'm no expert, but:

Take 'down by 3'/+3 modifier for example:

- The player with the modifier can't be drawn or beaten **at all** if he rolls 4 or more, because the overall score will be 7 or more.
- On 1xD6, there is a 3 in 6 (50%) chance of this situation.
- On 2xD6, there is a 27 in 36 (75%) chance of this situation, because there are only nine combinations in which **neither** die results in 4, 5 or 6.

So, from 50% chance of **completely unbeatable** to 75% chance. I'd say that's a big shift. This is what I was getting at.

However, I presume that your calculations are about the overall possibilities of an upset when you factor in all of the combinations — the bigger picture. Still, I'd say that those shifts are pretty significant. Granted, humans aren't great at assessing these things and it is somewhat subjective in any case — one person's 'too big' is another person's 'acceptable'.

To roughly refactor your figures and look at them another way:

Down by 5, 2.8% to 0.8% = (1 in 36) to (1 in 125)
Down by 4, 8.3% to 4.1% = (1 in 12) to (1 in 24)
Down by 3, 17% to 11% = (1 in 6) to (1 in 9)
Down by 2, 28% to 22% = (in 3.6) to (1 in 4.5)

I guess it all depends on personal attitude to the balance of risk — maybe some of us like more chance of an upset than others do.
I think that the crux of it for my friend and I is that we don't like the idea that (in the above example) there is a 27 in 36 chance that the disadvantaged player might just as well not even bother to roll dice...

**Comment by IJW-Wartrader** [comment]
The numbers come from this. I've lost the FB discussion thread at the moment, but this is the relative odds of different results with d6 and highest of 2d6.

<img width="929" alt="Combat resolution odds" src="https://user-images.githubusercontent.com/17686203/143455359-d04f42f0-374e-4261-9394-d2ad4b132a96.png">

But I think I was answering a slightly different issue than what you raised!

Yes, highest of two dice definitely increases the chance that the player with the upper hand can roll a result that can't be beaten. Personally, it doesn't bother me except for the reduction in usefulness for Counterattack re-rolls for the losing player, but if you're already 3-down then that's going to be a 'Hail Mary' attempt even if you're using a single d6.

The other reason it doesn't bother me too much is that the only place where it's 'easy' to get 3-up odds is in a firefight, where losing doesn't matter much unless you're already in a really bad situation. Getting 3-up in a close combat and having enough units in base contact for it to have a big impact requires a substantial investment of resources or having pulled off some impressive tactical manoeuvres.

**Comment by IJW-Wartrader** [comment]
Anecdote time - in the last-but-one game, I managed to get 2-up in close combat against a Warlord Great Gargant (cost 480pt).

This involved shooting it with about 400pt of troops in the previous turn, followed by 500pt in the current turn, followed by charging it with 200pt of insanely good close combat monsters (two C'Tan and my Supreme Commander). 

(Not that it's relevant to this discussion, but I rolled double 1 for combat resolution anyway, spent two Fate Cards so I could re-roll both dice, and rolled double 1 again! 🤣)

**Comment by digi-brain** [comment]
>The other reason it doesn't bother me too much is that the only place where it's 'easy' to get 3-up odds is in a firefight, where losing doesn't matter much unless you're already in a really bad situation. Getting 3-up in a close combat and having enough units in base contact for it to have a big impact requires a substantial investment of resources or having pulled off some impressive tactical manoeuvres.

3-up is just one example. For the 1-up example, the odds of an unbeatable result increase from (1 in 6) to (1 in 3). This might not bother you, but it does bother me.

To each his own I suppose. Perhaps you play it at a more 'expert' level where you want to reduce the effects of chance and reward careful positioning more, whereas perhaps I play it at a less exacting level where I'm happy to accept the existing level of chance upsets to even the most masterful positioning.

**Comment by IJW-Wartrader** [comment]
It's 11 in 36 not 12 in 36, but no it doesn't bother me. 

#It's an inherent part of this kind of opposed roll that the player with a higher modifier can get an unbeatable result. That doesn't make it pointless for the other player to roll, because the whole thing is a 'single' interlinked roll. And the same mechanism that's giving that player an unbeatable result is boosting the other player's roll to reduce how **much** they lose by, which is just as important as whether they lose.

**Comment by digi-brain** [comment]
> It's 11 in 36 not 12 in 36, but no it doesn't bother me.
> 
> It's an inherent part of this kind of opposed roll that the player with a higher modifier can get an unbeatable result. That doesn't make it pointless for the other player to roll, because the whole thing is a 'single' interlinked roll. And the same mechanism that's giving that player an unbeatable result is boosting the other player's roll to reduce how **much** they lose by, which is just as important as whether they lose.

True, but doesn't change my original point. Ultimately, it seems to boil down to this: Some of us are happy enough with the balance of chance in the original, and some of us aren't. A closer assessment of probabilities and such hasn't revealed anything fundamental to shift either viewpoint. So, it boils down to simple preference.

> But this is why it's only being mentioned as an option. You can carry on using the version you're happier with, and so can I.

Yes. That wasn't in dispute — we've just gone off on a tangent. Like I said, to each his own.

That said, the more I think about this, the more it seems like evangelising for a house rule. On that basis, I think the 'put it in a separate section' option (1st paragraph in quote below) is more appropriate than the 'put it alongside the actual default rules' option (2nd para). But if you're set on doing the latter then I'll go along with it.

>We could of course put all optional rules in a separate section, much like the experimental rules (and much like the "House rules and [blah blah]...." section in the original rulebook, except that we use some relationship links too).

>Or, at least some optional rules could be in the main content as you're suggesting. I'm not sure what should qualify for this treatment, versus what should qualify for the above. But if/where we do decide to take this route then I think the best thing is probably to have another note style especially for this purpose — perhaps NOTE.option or NOTE.optional? (I don't think that the semantics of it fit well with TIP.)

**Comment by IJW-Wartrader** [comment]
> That said, the more I think about this, the more it seems like evangelising for a house rule. On that basis, I think the 'put it in a separate section' option (1st paragraph in quote below) is more appropriate than the 'put it alongside the actual default rules' option (2nd para). But if you're set on doing the latter then I'll go along with it.

As per previous discussions, it was 'highly recommended' by Jervis Johnson. Epic 40,000 issue 8 page 6:

<img width="771" alt="2d6 high epic mag 8" src="https://user-images.githubusercontent.com/17686203/143575848-ca7a33c3-add0-46e8-b59c-bae57e206918.png">

Obviously that doesn't have the same strength as official errata or alternative rules, but they'd stopped doing errata for 3rd edition by that point.

So yes, I would like it to appear alongside the default rule.

In terms of formatting, in the current pull request https://github.com/GameBrains/er-core/pull/25 I used NOTE.option and put it in a partial, referencing the magazine issue.

**Comment by digi-brain** [comment]
Ah yes, I'd forgotten about that JJ bit. Another grey area in the continuum that includes 'experimental', 'unofficial', 'house rule', 'optional', etcetera. XD

Cool. I'm only dipping in briefly to work through notifications at the moment, between other things — but I'll get to that PR at some point and I'll add CSS for `NOTE.option`.

**Comment by IJW-Wartrader** [comment]
👍🏼👍🏼
