### ISSUE TITLE
Possible ability issues, classifying abilities

### ISSUE THREAD

**Issue by IJW-Wartrader** [GameBrains/er-core#35]
While starting the new abilities branch I've noticed a few bits that I think we need to look at.

### Apply the X ability rules
Abilities like Hero, Flak Battery, Siege etc. use an 'Apply the Save ability rules.' structure, and have both the `Data sheet modifier` and `Unit ability` tags.

This appears to be an error, as far as I know these are pure `Data sheet modifiers` that grant the unit the mentioned ability. The 'parent' ability is never used or referenced during a game, just the modified attribute values and the granted abilities.

Using Hero as an example:
What appears in the final calculated data sheet is a doubled Assault value, and Save in the Notes section. Hero is only shown in brackets (or is completely hidden, depending on view mode), as it has already been applied to the original data sheet. 

To put it a different way, on the tabletop we don't care if the unit has Hero, but what it's final Assault value is, and that it has Save.

**Proposal:** Replace 'Apply the X ability rules' with 'Add the X Ability'. Remove the `Unit ability` tag from these pages.

### Cavalry and Armour +1
I don't know Github well enough to work out how or when it happened (maybe in a merge?), but cavalry.adoc has lost its [NOTE.e40k] note saying that it has been split into two abilities, and has regained the bullet point saying 'Add +1 to its Armour value'.

**Proposal:** Re-add the note, and remove the bullet.

### Classifying abilities
Separate from the `Data sheet modifier` and `Unit ability` etc. tags, we currently have four classes of special ability, listed in two places:

- Official Epic 40k abilities, which form the bulk of the main ability list. For example Save, Assault, Cavalry, Ignore Terrain.
- New abilities that we have added, which are in the main ability list. For example Assault +1, Firepower +1. 
- Unused experimental Epic 40k abilities, which form the bulk of the experimental ability list. For example Bridge, Medic, Siege. Many of these are very unlikely to ever be used, or likely to be reworked substantially, so this is effectively just a placeholder list for abilities that were mentioned at some point by GW.
- New abilities that we have added, which are in the experimental ability list. I think this is just Robust at the moment.

What I'm unsure of is where to put the new abilities that have built up over the last half a year or so, and whether it might be worth splitting up the experimental ability list into unused obsolete abilities, and active abilities.

Deep Strike can probably go straight into the main list, as it's partially based on a GW note for Swooping Hawks, is widely used, and isn't controversial in any way.

For the rest, add them to the experimental list, and set a date to reevaluate if they're still experimental?

**Comment by IJW-Wartrader** [comment]
Related branch, currently with no commits to see: https://github.com/GameBrains/er-core/tree/abilities-update-may-2022

**Comment by IJW-Wartrader** [comment]
I think these abilities can go straight into the main list:

- Deep Strike (unit)
- Short/Medium/Long Range (modifier)
- Support (modifier)
- Has {super-heavy weapon} (modifier)
- Psychic Null (unit)

And these into the experimental list:

- CC Blast (detachment)
- FF Blast (detachment)
- Psychic Focus (detachment)
- Frenzy (detachment)
- Deamonbane (detachment)
- Markerlights (unit)
- Guided (unit)
- Target Lock (detachment)

**Comment by digi-brain** [comment]
> ### Apply the X ability rules
> Abilities like Hero, Flak Battery, Siege etc. use an 'Apply the Save ability rules.' structure, and have both the `Data sheet modifier` and `Unit ability` tags.
> 
> This appears to be an error, as far as I know these are pure `Data sheet modifiers` that grant the unit the mentioned ability. The 'parent' ability is never used or referenced during a game, just the modified attribute values and the granted abilities.

I don't think it was an error so much as a matter of perspective and process:

- If you do things the original way, then you're just writing 'As Space Marine' (or whatever) and then 'Hero' (or whatever) in the notes column of the data sheet.
- The builder gives a different perspective because it uses a record for every single individual calculated data sheet. You're now extending this perspective to the rules content.

Some people might still want to do it on paper, the old way, and calculate on the fly rather than writing every individual combination out in full.

But if you think it's better to make the latter the default in the rules content — and as long as you've given due consideration to the difference it implies for the pen and paper approach without the Builder — then I don't object to your proposal.

---

> ### Cavalry and Armour +1
> I don't know Github well enough to work out how or when it happened (maybe in a merge?), but cavalry.adoc has lost its [NOTE.e40k] note saying that it has been split into two abilities, and has regained the bullet point saying 'Add +1 to its Armour value'.
> 
> **Proposal:** Re-add the note, and remove the bullet.

Not a mistake. See your comment at https://github.com/GameBrains/er-core/issues/9#issuecomment-869932547 where you state:

> A slight case of scope creep - as discussed earlier, I edited Cavalry to add the Armour bonus back in, including in the example. The old note about separating the Armour bonus into Armour + 1 has been removed.

So, do you have a clear idea of the pros and cons of each approach and which way do you want to go now?

---

> ### Classifying abilities
> What I'm unsure of is where to put the new abilities that have built up over the last half a year or so, and whether it might be worth splitting up the experimental ability list into unused obsolete abilities, and active abilities.

There are several ways that we could approach this. My first instinct is that we should keep obsolete topics in the source code, at least for now, but comment them out of the respective `nav.adoc` file, so that they do not appear in the output. Then there is no need to divide the output into 'obsolete' and 'active' when the former is really just clutter anyway. They'll be gone as far as anyone else is concerned, but they'll still be in the project for us to refer back to or to potentially rework and bring to life in future.

For the new abilities that you propose to put straight into the main body of the rules: I'm not 100% up to speed with all of them, but go ahead if you're happy with them — nothing jumps out at me as problematic.

For those that go into the Experimental section: I think that we can simply move them over to the main body as and when we happen to feel/agree that a particular ability is sufficiently proven and accepted by the community. But it doesn't hurt to also have a rough idea of when we might make a point to review any see how we feel about any that might've gone under the radar for a while.

**Comment by IJW-Wartrader** [comment]
> > ### Apply the X ability rules
> > Abilities like Hero, Flak Battery, Siege etc. use an 'Apply the Save ability rules.' structure, and have both the `Data sheet modifier` and `Unit ability` tags.
> > This appears to be an error, as far as I know these are pure `Data sheet modifiers` that grant the unit the mentioned ability. The 'parent' ability is never used or referenced during a game, just the modified attribute values and the granted abilities.
> 
> I don't think it was an error so much as a matter of perspective and process:
> 
> * If you do things the original way, then you're just writing 'As Space Marine' (or whatever) and then 'Hero' (or whatever) in the notes column of the data sheet.
> * The builder gives a different perspective because it uses a record for every single individual calculated data sheet. You're now extending this perspective to the rules content.
> 
> Some people might still want to do it on paper, the old way, and calculate on the fly rather than writing every individual combination out in full.
> 
> But if you think it's better to make the latter the default in the rules content — and as long as you've given due consideration to the difference it implies for the pen and paper approach without the Builder — then I don't object to your proposal.

Short version, I think it's better as the default as it doesn't imply any changes for the pen and paper approach, and makes it easier to show calculated data sheets unambiguously.

Long version is long, because I want to make sure that I'm explaining my point of view properly and not leaving out information that would make this look more confrontational!

The main reason we split abilities into 'Data sheet modifiers' and 'Unit abilities' was because we wanted the ability to display final calculated data sheets, whether this was on pages on the Remastered site, in the builder, or elsewhere. In-game abilities like Save or Artillery always need to be displayed in the final calculated data sheet, and modifiers like Assault or Heavy Weapons _shouldn't_ be displayed because this introduces ambiguity where the player has to guess whether the displayed attribute values have been modified or not. It's _slightly_ like the problem with GW's [Kroot Hounds](https://thehobby.zone/resources/e40k-compendium/Content/Armies/ArmiesOfTheTau/TauUnitSummaries.htm), with Speed 20 cm and Cavalry. Is their final calculated Speed 20/30 cm, or Speed 40/60 cm? 

As a example, if a calculated Space Marine Captain datasheet shows an Assault value of 6 and has 'Hero' in the notes column instead of 'Save', this forces the player to make a mental check each time to remember if the Assault value has been doubled. Most of the time it's not an issue, but multiply it by lots of units, and players who might be unfamiliar with a faction's units, and it becomes a substantial readability and playability issue.

There were a tiny number of abilities like Jump Packs that needed to have both ability types listed, because they modify the attributes but _also_ have an in-game effect that isn't a named special ability. But as a general rule there should be no abilities that are both 'Data sheet modifiers' and 'Unit abilities', unless this would require creating a new ability. 

So on the one hand I can see where you think this is the builder forcing a different perspective onto the rules, but from my point of view it's a change that we decided on when we discussed how to display calculated data sheets in Remastered.

On the third hand, it's not necessarily a different perspective at all. Some of the E40k rules were written in the way I'm suggesting, and the change doesn't alter the pen and paper approach. Anyone writing out their list on paper still writes 'Space Marine with Hero', in the same way that they write 'Space Marine with Assault and Jump Packs', or 'Space Marine with Heavy Weapons', or 'Land Speeder with Hero'. 

This is also how it's shown in card view in the builder (and in the equivalent Remastered pages when we've sorted out the formatting), see https://builder.epicremastered.com/card.lc?list=Remastered_Chaos_CSM

GW, as usual, wrote these kinds of abilities several ways. 🤣

Hero: 'Hero [units] **have** a save'
Flak Battery: '**gain** the Flak special ability.'
Siege: '**count as having** the Close Support special ability'
Self-propelled Artillery: 'the [unit] **can now use** the artillery special rules'

----

> > ### Cavalry and Armour +1

> Not a mistake. See your comment at [#9 (comment)](https://github.com/GameBrains/er-core/issues/9#issuecomment-869932547) where you state:
> 
> > A slight case of scope creep - as discussed earlier, I edited Cavalry to add the Armour bonus back in, including in the example. The old note about separating the Armour bonus into Armour + 1 has been removed.
> 
> So, do you have a clear idea of the pros and cons of each approach and which way do you want to go now?

Ah, thanks, I was looking through the closed pull requests rather than the closed issues! There are now several units that have the Cavalry modifier without increased Armour, so I would like to go with increased Armour being completely split out from Cavalry.

----

> > ### Classifying abilities

> For those that go into the Experimental section: I think that we can simply move them over to the main body as and when we happen to feel/agree that a particular ability is sufficiently proven and accepted by the community. But it doesn't hurt to also have a rough idea of when we might make a point to review any see how we feel about any that might've gone under the radar for a while.

All your feedback and ideas for this bit sound good, especially the idea of setting some review deadlines.

**Comment by digi-brain** [comment]
I'm fine with all this, but just to clarify on that first bit:

I still say that the 'data sheet modifier + unit ability' duality wasn't an 'error' as such. So long as the language is "**Change** {value} on the data sheet {and} **Apply** the rules effects of the X ability..." then it makes sense I think. This duality niggled me a bit, but it wasn't something I saw fit to labour over at the time.

However, if we change the language to "... {and} Add the X ability" as you suggest, then yes — it becomes purely a data sheet modifier. That's a way to streamline what went before — an improvement rather than a correction of an error.

That was all I was really saying. It's a bit pedantic, but given the subtle procedural difference, I mentioned it in case there might be any other awkward thing to consider in relation to this. If you're happy that there isn't then it's all good and I like that your proposal would remove the current duality.

**Comment by digi-brain** [comment]
>GW, as usual, wrote these kinds of abilities several ways. 🤣

Lol, yes, pretty standard GW mish-mash.

**Comment by IJW-Wartrader** [comment]
This is one of the suggested fixes to make the Hierophant and Hierodule more resilient to Death Rays and sudden death by critical, so that their high Damage Capacity has more effect.

Short version - if a hit causes critical damage to the unit, roll a D6 and on a 4+ the critical damage is stopped with no need to roll on the Critical Damage Chart.

**Comment by digi-brain** [comment]
Ah, gotcha. Nice.

**Comment by digi-brain** [comment]
I added attributes for some of the new abilities to the playbook already as you know — I'll make time to add the rest soon, it's an easy job.

There's a bit of tension between 'interesting' and utilitarian ability names isn't there.

I agree that it might be better for _Bio-save_ to have more generic name, so it doesn't sound weird if we ever apply it to any units that don't have a good bio-based fluff excuse for it. Not crucial, but nice to have. In that case, I'd argue that while the likes of _Critical Resistance_ and _Critical Save_ are functional, they're rather bland and syllable-heavy. If we're forced to go utilitarian, then I'd suggest we at least keep it snappy — something like _Resistant_ or _Durable_. 

I still don't like _CC Blast_ and _FF Blast_ — but I guess these are just placeholders until we settle on proper names. I'm mulling over a couple more ideas on these at the moment.

**Comment by IJW-Wartrader** [comment]
> I agree that it might be better for _Bio-save_ to have more generic name, so it doesn't sound weird if we ever apply it to any units that don't have a good bio-based fluff excuse for it. Not crucial, but nice to have. In that case, I'd argue that while the likes of _Critical Resistance_ and _Critical Save_ are functional, they're rather bland and syllable-heavy. If we're forced to go utilitarian, then I'd suggest we at least keep it snappy — something like _Resistant_ or _Durable_.

Unfortunately those remove both of the possible bits of information we're trying to convey with the name! _Robust_ and _Dauntless_ are already bad enough for being semi-random adjectives, I have to reverse-search for _Dauntless_ almost every time by looking up _Synapse_ to get to the name of the 'auto-pass Leadership' ability!

If we don't choose a purely functional name, I would strongly like to find something that's as directly related to the ability as _Unbreakable_, _No Retreat_, _Rapid Fire_, _Save_ etc.

And if you can think of a name that's as directly related to auto-passing Leadership tests — to replace _Dauntless_ — I'd be extremely grateful!

----

> I added attributes for some of the new abilities to the playbook already as you know — I'll make time to add the rest soon, it's an easy job.

On that subject, for Short/Medium/Long Range there is a potential name clash as the _Long Range_ part is already allocated to the Vehicle Variant rule. But I'm not sure that's a big issue as GW never used the ability anyway, and we're commenting it out of the nav/adoc file.

**Comment by IJW-Wartrader** [comment]
Ooh, maybe _Bio-save_ doesn't need to be a separate ability? Refer to it as _Save (Criticals)_ and add it to the bottom of _Save_, slightly similar to _Supreme Commander_ listing the extra re-roll ability for the Dominatrix.

**Comment by IJW-Wartrader** [comment]
I've left Biosave under that name for now, and started a pull request: https://github.com/GameBrains/er-core/pull/36

**Comment by digi-brain** [comment]
> Unfortunately those remove both of the possible bits of information we're trying to convey with the name!

Yes, but that isn't essential, is it? The original ability names aren't all 'directly related' to specific rules concepts — many are merely *evocative*. _Rampage_, _Cavalry_, _Stubborn_, _Hero_ ...

---

_Robust_ and _Dauntless_ seem no worse than _Stubborn_ or _Rampage_ — we just aren't familiar with the former yet like we are with the latter. Or am I missing something?

> And if you can think of a name that's as directly related to auto-passing Leadership tests — to replace Dauntless — I'd be extremely grateful!

I fail to see how this is any different in principle to if you'd written:

> And if you can think of a name that's as directly related to re-rolling failed Leadership tests — to replace Stubborn — I'd be extremely grateful!

---

> On that subject, for Short/Medium/Long Range there is a potential name clash as the Long Range part is already allocated to the Vehicle Variant rule. But I'm not sure that's a big issue as GW never used the ability anyway, and we're commenting it out of the nav/adoc file.

Good point — but yes, as it wasn't really in use anyway I guess we shouldn't let it stop us. **Or**, I've just thought... what about a more flexible alternative:

- Rather than _Short/Medium/Long Range_, how about _Range (X)_, where X can be any value (typically 15, 30 or 45 — but could be 75 or whatever, if needed)?
- And as an extension to that thought — perhaps it'd be more consistent if we changed the likes of _Firepower +1_ to _Firepower (+1)_ instead?

---

> Ooh, maybe Bio-save doesn't need to be a separate ability? Refer to it as Save (Criticals) and add it to the bottom of Save, slightly similar to Supreme Commander listing the extra re-roll ability for the Dominatrix.

I think that there are quite different principles at work: The Dominatrix thing is in effect an extension an existing ability rule, for a special case. _Bio-save_ is a 'save' against a different effect to that which the _Save_ ability rule covers.

> I've left Biosave under that name for now, and started a pull request: #36

Probably best. If in future we come up with a more versatile name that feels right then great, we can change it.

**Comment by digi-brain** [comment]
> * Destiny, Not Fate (unit)

I wonder if it'd be better to make this simply _Destiny_? Not only because it'd be shorter (while still distinct), but also because then we wouldn't have a comma. Commas in inline lists, such as multiple abilities, can be confusing when you're already using the comma as the separator for list items.

If you're keen to keep the long version, then I'd suggest that you should change the builder so that all abilities are separated by semi-colons rather than commas. (That's actually good practice in many 'inline list' contexts, precisely because it avoids confusion around commas.)

**Comment by IJW-Wartrader** [comment]
> > * Destiny, Not Fate (unit)
> 
> I wonder if it'd be better to make this simply _Destiny_? Not only because it'd be shorter (while still distinct), but also because then we wouldn't have a comma. Commas in inline lists, such as multiple abilities, can be confusing when you're already using the comma as the separator for list items.
> 
> If you're keen to keep the long version, then I'd suggest that you should change the builder so that all abilities are separated by semi-colons rather than commas. (That's actually good practice in many 'inline list' contexts, precisely because it avoids confusion around commas.)

In the commit I left out the comma. I do agree that a shorter term would be better, but _Destiny_ suffers all the above issues of being an abstract term, and isn't very directly evocative. _Destiny not Fate_ at least includes 'Fate' which links it mentally to Fate cards.

Hmm. _Controlled Fate_?

**Comment by digi-brain** [comment]
W.r.to ability names, I'll come back to that when I've got more time to figure out how to articulate my thoughts.

---

> I'd been wondering along similar lines! Although as a data sheet _modifier_ I think _Range (+X)_ with values of +15/-15 etc. would work better, and be consistent with _Firepower (+1)_, _Assault (+1)_, and _Armour (+1)_

Yes. I leant **mildly** in favour of 'absolute' when we discussed _Short/Medium/Long Range_. But in the context of this variation on the idea, I agree that it might be slightly better to go 'relative', in line with the other datasheet modifiers, as you suggest.

> Although I do have a concern that this moves too far away from the original concept of targeted data sheet modifiers, because it becomes possible to make almost _any_ unit from a given starting point unit.

I'm not sure I understand. We're just making sure that we have a complete toolkit, aren't we? Just don't get carried away and use every tool at once on a given unit!

---

>In the commit I left out the comma. I do agree that a shorter term would be better, but Destiny suffers all the above issues of being an abstract term, and isn't very directly evocative. Destiny not Fate at least includes 'Fate' which links it mentally to Fate cards.

Strictly, it should have the comma — but I could live without it. Or the comma wouldn't matter if we switch to a semi-colon separator, as I mentioned (but I understand that it might not be worth the effort to switch at this point if comma separators aren't causing any other trouble).

>Hmm. _Controlled Fate_?

As to _Destiny, not Fate_ versus _Destiny_ or _Controlled Fate_ — again, I'll post again on ability names when I have more time.

**Comment by digi-brain** [comment]
I've added the new ability names and placeholders to the playbooks, [as they currently stand in your comment near the top of this thread](https://github.com/GameBrains/er-core/issues/35#issuecomment-1132946566). As usual, we can refine at any time later as needed.

**Comment by IJW-Wartrader** [comment]
I've finally found time to sit down and do a new commit, which includes the proposed change for Rapid Fire, from FPx2 to FP+1.

Portal has had a major rewrite, and I've changed 'Portal Reserves' to a placeholder to make the page easier to update in the future.

**Comment by digi-brain** [comment]
Cool, sounds good. As we get into Autumn and Winter, I hope to make some time to move things along a bit as well — I've barely touched the project for ages.

I did play a couple of solo mini-games though in the past week, so that's something — 750 points (5 detachments) per side. Rather than taking over the dining room with my games table, I cleared my hobby desk and played on a 60 x 90 cm area of battle mat, and halved all distances throughout the games. Not ideal of course, but it worked okay and better than nothing for a bit of a refresher.

I'll be glad when we can write up a proper explanation of HTF the extended In Command range of the _Infiltrators_ ability actually works in different situations... 🤣

**Comment by IJW-Wartrader** [comment]
> I'll be glad when we can write up a proper explanation of HTF the extended In Command range of the _Infiltrators_ ability actually works in different situations... 🤣

Yeah... 💩

To be honest, I've been restricting myself to using the 'deploy/move 30 cm further' part and keeping the units within the regular 30 cm command range, just to avoid dealing with the weirdness. 🤣

The mini-games sound like a good way of doing stuff with limited room/time.

**Comment by IJW-Wartrader** [comment]
I think this can be closed.

I'll need to update a few of the newer abilities to match the updated versions in the builder, but that will be a new issue and branch.
