### ISSUE TITLE
Super-heavy weapon plans, war engine weapon mounts

### ISSUE THREAD

**Issue by IJW-Wartrader** [GameBrains/er-core#7]
Expanding the side note about super-heavy weapons needing to lock on, because it's relevant here, plus a couple of slightly-related points...

### Lock on

Although the Shooting phase doesn't currently mention the need to lock on with SHWs, I think it's worth adding a note or calling it out in S3, and saying that it applies whenever that unit's or detachment's Firepower is halved. Then use similar text (or a partial?) on the main Super-heavy weapons page.

This will make the Critical Damage tables slightly simpler as they won't need to spell out the need to lock on, the overall rules text is more consistent, and it would cover future edge-cases like a detachment that has the Dodge ability and can include units with SHWs.

### Shooting with super-heavy weapons

In super-heavy-weapons.adoc > Shooting with super-heavy weapons, you've got a TODO note asking about how locking on works if not using war engine orders. This isn't relevant for two reasons - all sources of halving Firepower that I can think of also require SHWs to lock on, so it's not linked just to Assault orders, and secondly there are a lot of regular units that carry an SHW! ;)

### War engines, suppression, splitting fire, and locking on

This point is more speculative, and I need to bring it up in the FB groups. There are a bunch of FAQs about how Blast markers and SHWs work, text in the war engine rules for not splitting fire from one battery, and one of the Armageddon intro articles where Jervis tears his hair out talking about how misunderstood this all was, and how Blast markers applying per model fixed all this for Armageddon. A case in point being the three FAQs for Pulsars, all repeating that it's a single SHW for inflicting Blast markers, for being shut down by Blast markers, and for firefights.

Because...

Within the Epic 40k rules, as far as I can see, there was a concept of a 'war engine weapon mount' which was the smallest sub-division of firing for war engines. But this was never spelled out.

**Proposal** - all war engines have a number of weapon mounts, on data sheets this is each separate weapon line. for example a Warlord has four (left arm, right arm, left carapace, right carapace), while a Baneblade has one (turret guns), and a Shadowsword has two (Death Ray, sponson turrets).

A weapon mount:
- Cannot split fire between target detachments.
- Is a single weapon for criticals that destroy a weapon or limit the war engine to firing one weapon.

In addition, a weapon mount that does not have a normal Firepower value* counts as a single super-heavy weapon for the following purposes:
- Being suppressed by Blast markers.
- Inflicting Blast markers.
- Rolling to lock on.
- Adding up Firepower in a firefight.

*So everything that isn't a heavy weapon battery or the Firepower part of a Close Combat Weapon.

_Originally posted by @IJW-Wartrader in https://github.com/GameBrains/er-core/issues/5#issuecomment-853076794_

**Comment by IJW-Wartrader** [comment]
The SHW and war engine weapon mount discussion moved to a new new discussion.

Other related bits, in no particular order:

**Picking targets**
The main page for SHWs talks about picking out targets. This is outdated, so I propose moving this to the SHWs that still use it, so Death Ray, Distrortion Cannon, and Supa Lifta Droppas.

**Types of SHW**
Roughly speaking, there are SHWs that pick out individual targets (see above), ones that add to the overall Firepower (Barrage and Heavy Barrage), other templates (Mega Cannon, missiles), and Macro-Weapons.
I don't think we need to separate these like the special abilities, but bearing in mind these four 'types' will help us with the content, and working out which ones need to mention which targeting methods.

**Template partials**
As discussed at some point, we need to add one or more partials for templates, whether that's for their whole placement or for working out whats affected by a template.

**Close Combat Weapons and 'hits'**
Note to self, if you win against a war engine, the roll on the Catastrophic Damage Chart **is not a hit**. It therefore does not interact in any way with a Save of Holo-field and cannot be stopped.

**Comment by IJW-Wartrader** [comment]
Summarising templates, very roughly...

**Barrages**
- Place the template completely within range and line of sight of all units contributing to the barrage attack. (Add an exception for units with Artillery, who don't need line of sight.)
- Work out who is covered by the template:
- - Infantry whose base centre is covered.
- - Vehicles and war engines whose base is touched or covered.
- The template must be placed to cover as many units as possible from the target detachment.
- The number of covered enemy units from the target detachment is the Firepower value for each Barrage unit contributing to the attack.
- This is added to the total Firepower that the detachment is directing at the target detachment, including for the purposes of inflicting Blast Markers.

NOTE: Barrages simply add to Firepower, so the Firepower table and hit allocation rules are applied normally. The units covered by the template may not be the units that get hit!


**Other templates**

- Place the template completely within range and line of sight. (Add an exception for units with Artillery, who don't need line of sight.)
- Work out who is covered by the template:
- - Infantry whose base centre is covered.
- - Vehicles and war engines whose base is touched or covered.
- The template does **not** need to be placed to hit a specific detachment, and does **not** need to hit as many units as possible.
- Roll to hit each individual unit covered by the template. Unlike a Barrage, these are the only units that can be hit by the weapon.

**Comment by digi-brain** [comment]
All sounds sensible to me, I can't see any problems. For placement of templates, a partial is definitely the way to go so that we can single-source the common parts.

I have an idea that relates to this:

>Who is covered by the template?
> * Infantry whose base centre is covered.
> * Vehicles and war engines whose base is touched or covered.

I do like that in EA, standard barrage weapons only get **full** effect against war engines if the centre of the template is somewhere over the war engine, not merely overlapping or touching (half effect). Could we adapt that for Remastered, or is it fundamentally different? I mean, do E40k artillery get [ {starting damage capacity} amount of Firepower] against war engines? If they do then surely we can apply the same idea as for EA, but with Firepower rather than number of dice to hit?

**Comment by IJW-Wartrader** [comment]
> I do like that in EA, standard barrage weapons only get **full** effect against war engines if the centre of the template is somewhere over the war engine, not merely overlapping or touching (half effect). Could we adapt that for Remastered, or is it fundamentally different? I mean, do E40k artillery get [ {starting damage capacity} amount of Firepower] against war engines? If they do then surely we can apply the same idea as for EA, but with Firepower rather than number of dice to hit?

War engines are just a single unit for Barrages in E40k.

I did look into an EA-style approach at some point, but the fundamental differences in the base mechanics stop it working. :( Mainly the difference between one template in E40k and no overlapping templates in EA, and then exacerbated by DC values being higher in E40k.

Starting with the 'obvious' option of counting the war engine as half its starting DC if the template is in the 'right place', because that's where I started as well:
1. A Warlord is DC12. 
2. If the template is in the right place, the Firepower value for **each** Barrage unit is 6.
3. The total Firepower values then get absurdly high, very quickly. For example, half a dozen Whirlwinds get Firepower 36 against a Warlord, which would be impossible in almost any other situation as it would require an incredibly densely-packed target detachment.

Now apply that to the WEs with actual high DC values, like Gargants and Hierophants with DC18 (Firepower 54), or Mega Gargants and Imperators with DC24 (Firepower 72). Even a single Multiple Rocket Launcher on a Titan (or any other Heavy Barrage weapon) would get Firepower 24 against an Imperator.

We could look at 'Starting DC/8' or similar, so that Warlords, Gargants and Great Gargants count as 2, while Imperators and Mega Gargants counts as 3, but I'm not sure it's worth the hassle and the inconsistency with all the 'Starting DC/2' and 'Current DC/2' rules.

**Comment by digi-brain** [comment]
Okay, I can see that it does get absurd fast! And I agree it really wouldn't be worth the hassle to have DC/8 rules... much too fiddly.

To take a less extreme example, with four rather than six Barrage units: It is perhaps a little odd that as it stands four Barrage units would get FP4 against a Warlord titan, no matter how much or how little of the template is overlapping. And they'd get the same against a much smaller super-heavy tank. Although, if there are other targets nearby, the compensation would be some Firepower on those too.

In contrast, it wouldn't be all that uncommon to catch four Infantry/Vehicle units under the template instead and thus get FP16.

Maybe it could be something to the effect of if you get the centre of the template over the war engine then you get double Firepower? (Though we'd have to consider what happens with Heavy Barrage, which already does that...)

I dunno, just ideas. It's a tangent to the main thrust of this issue, so we can drop it here if you like. If we decide later that the **general** idea has merit then we can create a new issue and see if we can find a specific way to make it work sensibly.

**Comment by IJW-Wartrader** [comment]
Note to self: Supa Lifta Droppa text needs to be updated so that it doesn't say all Vehicles are DC1.

**Comment by IJW-Wartrader** [comment]
> Maybe it could be something to the effect of if you get the centre of the template over the war engine then you get double Firepower? (Though we'd have to consider what happens with Heavy Barrage, which already does that... though without the 'centre' requirement, so maybe that's okay too.)
> 
> 
> 
> I dunno, just ideas. It's a tangent to the main thrust of this issue, so we can drop it here if you like. If we decide later that the **general** idea has merit then we can create a new issue and see if we can find a specific way to make it work sensibly.

I suspect we should leave the Barrage and WE interaction unchanged for now, but this seems like a sensible place to discuss future ideas.

FP2 if the template is in the right place seems OK as a blanket rule, Heavy Barrage would double that as normal.

Bear in mind that Barrages default to targeting a single detachment, so catching other nearby units under the template isn't really relevant.

**Comment by digi-brain** [comment]
>FP2 if the template is in the right place seems OK as a blanket rule, Heavy Barrage would double that as normal.

Or, as an option if doubling again seems too much, just make Heavy Barrage apply even for 'touch' rather than 'centre of template over the war engine' -- this would still give Heavy Barrage a boost over Barrage, but without quadrupling the Firepower. Just an idea - perhaps quadruple is okay in this case.

>Bear in mind that Barrages default to targeting a single detachment, so catching other nearby units under the template isn't really relevant.

True in theory, but IIRC given that you only need to 'touch' a WE with the template, other caveats could kick in quite easily couldn't they? Such as:

* Barrage: "as many enemy units as possible" can easily mean more than one detachment.
* FAQ: Barrages "if two detachments are completely intermingled they should be both fair game to be targeted by the same barrage"
* War engine detachments: Could catch more than one war engine, and you will if you can in the absence of any incentive to shift the template onto one of them.

**Comment by IJW-Wartrader** [comment]
> > FP2 if the template is in the right place seems OK as a blanket rule, Heavy Barrage would double that as normal.
> 
> Or, as an option if doubling again seems too much, just make Heavy Barrage apply even for 'touch' rather than 'centre of template over the war engine' -- this would still give Heavy Barrage a boost over Barrage, but without quadrupling the Firepower. Just an idea - perhaps quadruple is okay in this case.

I don't think it would be sensible to have Barrage and Heavy Barrage behave differently from each other against one specific type of target. Heavy Barrage is Barrage x 2, and I think we should stick to that everywhere.


> True in theory, but IIRC given that you only need to 'touch' a WE with the template, other caveats could kick in quite easily couldn't they? Such as:
> 
> * Barrage: "as many enemy units as possible" can easily mean more than one detachment.
> * FAQ: Barrages "if two detachments are completely intermingled they should be both fair game to be targeted by the same barrage"
> * War engine detachments: Could catch more than one war engine, and you will if you can in the absence of any incentive to shift the template onto one of them.

See up-thread, the current working text is 'Covering as many units as possible **from the target detachment**'. This is because the original GW Barrage text had a logical 'leap' from covering as many units as possible to then ignoring any of them that weren't from the target detachment. If we want to work in the FAQ about intermingled formations in some more formalised way, it's even more important to specify 'from the target detachment' to prevent people trying to straddle multiple detachments whenever possible to spread out more Blast markers.

**Comment by digi-brain** [comment]
> I don't think it would be sensible to have Barrage and Heavy Barrage behave differently from each other against one specific type of target. Heavy Barrage is Barrage x 2, and I think we should stick to that everywhere.

Well, it's not that Heavy Barrage would cease to be functionally equivalent to Barrage x 2 -- rather, it's that Barrage would become functionally equivalent to Heavy Barrage when the centre of the template is over the war engine. But yes, perhaps that isn't as neat as we'd like — less-worse than the craziness that results from the Damage Capacity-based idea is a low bar to cross, and we'd like to do better than that. >-D

---

> the current working text is 'Covering as many units as possible from the target detachment'.

Ah, okay. That makes sense, though as currently written, against a detachment comprised of a single war engine you could touch one war engine and meet the requirement ("as many as possible" - there is only one) and still aim to touch/cover other stuff nearby.

**Comment by IJW-Wartrader** [comment]
I've started the branch for this, as it should have little overlap with the Special abilities branch.

**Comment by IJW-Wartrader** [comment]
Barrage and Mega Cannon updated and pushed to the server, including example diagrams and edition change notes.

**Comment by IJW-Wartrader** [comment]
There was a comment somewhere about 'fire arc' versus 'weapon arc', but it's no longer visible in the pull request.

I agree that 'weapon arc' would be better, and had already been thinking along the same lines.

**Comment by digi-brain** [comment]
>There was a comment somewhere about 'fire arc' versus 'weapon arc', but it's no longer visible in the pull request.
>
>I agree that 'weapon arc' would be better, and had already been thinking along the same lines.

Yes, it was in a conversation that went 'Outdated' after I pushed edits. I resolved the conversation with the thought that you'll either find it or I'll bring it up again on the more relevant topic.

Okay, we're agreed then. I've already started to edit the topic and this is a minor change, so I think it's easiest if I continue to edit and then you verify the rules continuity in my edits as usual.

Per one of our other conversations, I'm minded to add something to the effect that the arcs constrain the line of fire for the weapon in that mount. A small gripe about that is that again we have the word 'fire' where it isn't always warranted because weapon arcs apply to CCWs and tentacles that have no ranged component. I'm happy to ignore this quibble for now, but I think that it is another point in favour of a global change from 'line of fire' to 'line of sight'.

**Comment by IJW-Wartrader** [comment]
> Per one of our other conversations, I'm minded to add something to the effect that the arcs constrain the line of fire for the weapon in that mount. A small gripe about that is that again we have the word 'fire' where it isn't always warranted because weapon arcs apply to CCWs and tentacles that have no ranged component. I'm happy to ignore this quibble for now, but I think that it is another point in favour of a global change from 'line of fire' to 'line of sight'.

A very very minor point is that a 'line of fire' is inherently limited by a 'fire arc', and that the fire arc text already says that you can only use the weapon against targets within the arc. But if you think it's better to specifically spell out that the arc  includes restricting los/lof then do so!

**Comment by digi-brain** [comment]
>A very very minor point is that a 'line of fire' is inherently limited by a 'fire arc'...

Yes, but if we do not clearly **state** that the specific game concept of 'line of fire/sight' is constrained by weapon arcs, then I fear that it can be too easy to overlook or even a bit ambiguous in some contexts. As far as I can recall we haven't actually made an explicit link between the concepts -- we've just assumed that people understand that it is inherent.

Yes, I think I'll go ahead and spell it out — it'll only take a small tweak to do it.

**Comment by IJW-Wartrader** [comment]
shooting-with-war-engines.adoc and weapon-mount-examples.adoc

As this is about two pages, I thought it would be easier to discuss here rather than in the pull request.

I'm a bit lost with the references to weapon mounts 'holding' weapon systems. Have you spotted a new issue that stops us treating 'weapon' and 'weapon mount' as near-synonyms?

**Comment by digi-brain** [comment]
I can't remember my exact reasoning right now without looking back at the earlier version, but:

One of things I had in mind was that there could be more than one weapon in a weapon mount (I think you said something about this in a conversation we had the Death Ray topic?). I think that there was some tension with weapon/weapons that complicated the near-synonym. Or there might've been some other thing 

I did have the feeling that something about the continuity of the 'near-synonym' was off, and that actually why I started to change it -- I'm still working through it at the moment, because these topics are especially tricky to nail down. But I'll be extra alert on my next look at those bits. It's also possible that there was something amiss, but that I've also missed some connection and have stumbled into a more complicated way to solve it than is necessary.

When you say you're 'a bit lost', do you see something particularly problematic? If so then let me know, but if it's just a bit unclear at the moment I suggest to let me finish my current pass on it, and then let's see if it makes sense or if there is still a problem. Does that sound okay? I think that you're right to query this, but it is awkward to unpick at the moment because I'm only part-way through and a single 'editing pass' can take me several commits, depending on complexity and available time.

**Comment by IJW-Wartrader** [comment]
> One of things I had in mind was that there could be more than one weapon in a weapon mount (I think you said something about this in a conversation we had the Death Ray topic?). I think that there was some tension with weapon/weapons that complicated the near-synonym. Or there might've been some other thing

Sort of, but it was the other way around. It's that a weapon mount can have more than one shot, rather than more than one weapon.

So a 'Melta Cannon' weapon mount has a Range of 15 cm and a Firepower of 4 x Death Ray.

But I think the bit that persuaded you previously was 'Heavy Weapon Batteries'. These aren't defined as 'weapons' anywhere, they're just a weapon mount that has Range and Firepower characteristics.

> When you say you're 'a bit lost', do you see something particularly problematic? If so then let me know, but if it's just a bit unclear at the moment I suggest to let me finish my current pass on it, and then let's see if it makes sense or if there is still a problem. Does that sound okay? I think that you're right to query this, but it is awkward to unpick at the moment because I'm only part-way through and a single 'editing pass' can take me several commits, depending on complexity and available time.

Roughly speaking, having thought about it a bit more:

If you want to have separate 'weapon mount' and 'weapon system' concepts, you have to define what a 'weapon system' is, and it's going to have massive overlap with the 'weapon mount' concept. The purpose of adding 'weapon mounts' was to give everyone a concept that covers a single 'weapon' that can have multiple SHW shots without being able to split fire with those shots, and have all the shots be suppressed in one go, and that can alternatively have a plain Firepower value. And at the same time, covers 'weapons' that just have Range and Firepower.

I think you've spotted a gap in the concept, but I'm worried that adding a separate concept is going to be a wild goose chase, and that it's the 'weapon mount' concept that needs a bit more explanation.

Note that in the long run, I would like to get rid of 'Pulsar' as a class of super-heavy weapon, as it's completely covered by listing a weapon mount with Range 60 cm and Firepower D6 x MW. Much in the same way that GW already did this with Revenant Scout Titans, who have non-existent 'Pulse Lasers' with Range 45 cm and Firepower D3 x AT.

**Comment by digi-brain** [comment]
>Sort of, but it was the other way around. It's that a weapon mount can have more than one shot, rather than more than one weapon.

Ah, okay -- I think that explains it. That helps, I should be able to edit this aspect much more cleanly now. The 'weapon system' thing was nagging at me too, and was hoping that all would become clear by the time I worked through it all, which sometimes happens. Somehow I latched onto 'multiple weapons' in my mind, but now that I understand it should actually be 'multiple shots' it makes a lot more sense.

I might've gotten that at a different time if I stepped back in wider 'writing mode' -- sometimes the narrow focus of 'editing mode' has its drawbacks!

**Comment by digi-brain** [comment]
Also:

>So a 'Melta Cannon' weapon mount has a Range of 15 cm and a Firepower of 4 x Death Ray.

This conflicts a bit with the idea that the 'weapon mount' is something like 'arm' or 'carapace'. So, something to tighten up or define there too perhaps.

**Comment by digi-brain** [comment]
>Ahhh, okay -- I think that explains it. That helps, I should be able to edit this aspect much more cleanly now.

It **does** help, but it still isn't as clean as I'd like. It is surprising how tricky it is to solve little logical gaps that I'm finding when I try to make the terminology as robust as possible.

Essentially, it is troublesome because a weapon mount can manifest as any one of these things:

* A weapon system that provides a single super-heavy weapon shot, such as {death-ray}.
* A weapon system that provides multiple super-heavy weapon shots, such as a Melta Cannon (which provides several {death-ray} shots). 
* A weapon system that provides a basic Firepower value, such as a Heavy Weapons Battery.
* A weapon system for close combat, such as {close-combat-weapons} or {ripper-tentacles}.
In some cases such a system may also provide a basic Firepower value.

It's hard not to use 'weapon system' in some sense or other here, especially when you're trying to keep the sense that one lot of 'stuff' in a mount is suppressed by a single Blast marker (except when it is a system that has a basic Firepower value).

It also might've been a bit easier if super-heavy weapons had been called 'weapon effects' or something like that instead, while the actual weapon is called Melta Cannon or whatever and the mount is called arm/carapace/whatever.

 I'll play around with it some more soon and share what I've got. You might see another way through it.

**Comment by digi-brain** [comment]
Right, I've pushed some changes for these two topics (and also `super-heavy-weapons.adoc`, but that is mostly incidental).

It's longer than I'd like in an ideal world, but hopefully robust at least, with a logical flow. I've introduced 'weapon mounts' and 'weapon arrays' as separate but related concepts. We could use 'systems' instead of 'arrays', but I thought I'd try this as perhaps it feels more specific -- 'weapon system does already exist once in the project in a general sense, but we could change that.

See what you think.

**Comment by IJW-Wartrader** [comment]
Initial thoughts:

> Each War Engine unit has one or more weapon mounts. These are simply the weapon-carrying locations on the war engine, and have names like Left Carapace or Turret Guns.

If we're separating the concepts of mounts and arrays/systems, we need to separate their names as well. 

- 'Left Carapace' is the name of a mount.
- 'Turret Guns' is the name of an array.

Fully expanded and using the names on the E40k data sheet, a Baneblade has:
- A Main Weapons mount with All-round 360º arc, containing a Turret Guns array, which has Range 45 cm and FP8.

While a Shadowsword has:
- A Main Weapons mount with Front 90º arc, containing a Volcano Cannon/Plasma Blastgun array, which has Range 60 cm and a Death Ray shot.
- A Secondary Weapons mount with All-round 360º arc, containing Sponson Turrets, which has Range 30 cm and FP2.

And an Ork Battle Fortress has:
- An unnamed mount with All-round 360º arc, containing a Gunz array, which has Range 45 cm and FP8.

Very roughly speaking, all war engine data sheets that have fixed weapon choices like the Battle Fortress, Leviathan, Hellbore, Plague Tower, and most of the Dominatrix, have a single name for both the mount and the array.

When a unit has fixed weapon options, most of the time it's going to be easier for both the data sheets and the players to use the array name directly:
![shadowsword-card](https://user-images.githubusercontent.com/17686203/124588582-e2473700-de50-11eb-922d-9d6b3bf65115.png)

---

**Naming summary:**
I think on the main Shooting with war engines page we can just change 'Turret Guns' to 'Right Arm'. But the Weapon mount examples page obviously needs quite a lot of work. ;-)

**Comment by IJW-Wartrader** [comment]
Note that I've added a few comments to Weapon mount examples in the pull request, but only where you already mentioned rules concerns.

**Comment by digi-brain** [comment]
>If we're separating the concepts of mounts and arrays/systems, we need to separate their names as well.
>
>- 'Left Carapace' is the name of a mount.
>- 'Turret Guns' is the name of an array.

Quite right. The two separate logical sets of names is the main thing that drove me to separate these things; there seemed to be some inescapable logical inconsistencies when they were all mixed up. I had Turret Guns in an earlier iteration when it was all mixed, and hadn't caught up with that yet (similarly, I haven't fixed the examples yet -- much easier to do once the main idea is reasonably stable).

Similarly, Melta Cannon and other titan weapons would be an array, of course.

>When a unit has fixed weapon options, most of the time it's going to be easier for both the data sheets and the players to use the array name directly:

I think that's fine. I believe that it is important to have a clear foundation in the rules, a 'full explanation' to fall back on -- but then also okay to use 'shorthand' on data sheets and such, where it makes sense. I went down the 'full explanation' path because everything else I tried was problematic and left some kind of logical gap in the phrasing.

I expect that we'll want to rationalise some of the names of things on data sheets. Eg, Baneblade could have Turrets mount rather than Main Guns mount -- or as you say, we don't mention the name of the mount at all if it works out better to just name the array and conflate the two in shorthand. 

You haven't mentioned any fundamental flaws so it sounds like aside from small inconsistencies to iron out  of the draft, and knowing that we'll use shorthand in some places... it all makes sense?

In that case, nomenclature: Do you think of 'weapon array' versus 'weapon system'? To me, the former seems more specific and perhaps that is useful for disambiguation — and the latter seems more of a 'natural' fit.

**Comment by IJW-Wartrader** [comment]
> (similarly, I haven't fixed the examples yet -- much easier to do once the main idea is reasonably stable)

Exactly.

> You haven't mentioned any fundamental flaws so it sounds like aside from small inconsistencies to iron out of the draft, and knowing that we'll use shorthand in some places... it all makes sense?

As much as I'd love to find a way to recombine them, I don't think it would work.

> In that case, nomenclature: What do you think of 'weapon array' versus 'weapon system'? To me, the former seems more specific and perhaps that is useful for disambiguation — and the latter seems more of a 'natural' fit.

My personal preference would be 'weapon system' because 'array' strongly infers plurality, which isn't true for options like a 'Volcano Cannon', 'Quake Cannon', Vortex Missile etc. While 'system' covers both singular and plural.

Searching through the files, 'weapon system' is only used in Close Support and Anti-Personnel weapon, where it's just flavour text and easy to change.

**Comment by digi-brain** [comment]
Okay, great. I'll fix up those details on another pass soon.

>My personal preference would be 'weapon system' because 'array' strongly infers plurality, which isn't true for options like a 'Volcano Cannon', 'Quake Cannon', Vortex Missile etc. While 'system' covers both singular and plural.
>
>Searching through the files, 'weapon system' is only used in Close Support and Anti-Personnel weapon, where it's just flavour text and easy to change.

I was coming to much the same conclusion. Okay, also great, 'weapon system' it is.

**Comment by digi-brain** [comment]
Oh, the other one that is slightly odd, which doesn't show up in a simple search for 'weapon system':

>Where your War Engine unit is armed with {ripper-tentacles}:
>
>* When it fights against one or more enemy War Engine units in close combat, choose one {close-combat-weapons} system.
>The {ripper-tentacles} wrap around and trap that system, which means that the enemy gains no benefit from it for this close combat.

Arguably, this one works as-is, particularly as CCWs only exist on war engines anyway! But, I also wonder if it should be less specific to {close-combat-weapons}, and more general to 'close combat weapon systems'...?

That is, would we like to leave room for some more interesting close combat-focused titan weapons than just the generic {close-combat-weapons}? Or are we never likely to have different special rules for any of those anyway? Just a thought — we can cross that bridge if we ever come to it. But let me know if you think that there **is** a problem with the current phrasing as far as our new 'weapon systems' go.
